# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Accueil
    url: /#top
    weight: 10
  - name: Prowellness
    url: /#features
    weight: 20
    hasChildren: true
  - parent: Prowellness
    name: Présentation
    weight: 21
    url: /prowellness
  - parent: Prowellness
    name: Feel Great
    weight: 22
    url: "https://ufeelgreat.com/fra/fr/c/marc.nguyen"
  - parent: Prowellness
    name: Detox
    weight: 23
    url: /detox
  - parent: Prowellness
    name: Métabolisme
    weight: 24
    url: /metabolisme
  - parent: Prowellness
    name: Immunité
    weight: 25
    url: /immunite
  - parent: Prowellness
    name: Tous les produits
    url: /product/
    weight: 26
  - name: Qui suis-je?
    url: /about
    weight: 30
  # - parent: Qui suis-je?
  #   name: Santé
  #   weight: 1
  #   url: /#sante
  # - parent: Qui suis-je?
  #   name: Mindset
  #   weight: 2
  #   url: /#mindset
  - name: Resources
    weight: 40
    hasChildren: true
  - parent: Resources
    name: Blog
    weight: 1
    url: /blog/
  - parent: Resources
    name: Ebook Prowellness
    weight: 2
    url: /ebook
  - parent: Resources
    name: Science
    url: https://www.unicityscience.org/?lang=fr
  - parent: Resources
    name: Histoire Unicity
    url: https://www.unicity.com/fra/fr/learn/history
