# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/


# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: 'Santé'
    org_name: 'Life with Health and Quality'
    description: 'Un leader dans la santé métabolique, dans le développement personnel et dans les revenus passifs orientés vers la liberté financière.'
    twitter: 'marcbetterlife'
    facebook: 'marcnguyen.betterlife'
    tiktok: 'marcnguyen.betterlife'
    instagram: 'marchh.nguyen'
  analytics:
    google_analytics: 'G-04M46XQ66M'
    microsoft_clarity: 'nkirsl36ml'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: 'G-04M46XQ66M'
    bing: 'nkirsl36ml'
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo3.jpg"
    button:
      enable: true
      text: "Feel Great"
      url: "https://ufeelgreat.com/fra/fr/c/marc.nguyen"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice:   '© {year} Marc Nguyen'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
